version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 10

    commands:
      - npm i -g serverless@1.60.0
  post_build:
    commands:
      - serverless deploy --region ap-southeast-2 --verbose